spring.application.name=backend
# ============================
# Base de datos PostgreSQL (Render)
# ============================
server.port=8620
spring.datasource.url=jdbc:postgresql://dpg-d7duj4rbc2fs73e8sd5g-a.oregon-postgres.render.com/streetwearbd
spring.datasource.username=streetwearbd_user
spring.datasource.password=52bEnDRSbKsXbbDgZHbybmEktBwblPa5
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

